# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.






# Brute force:
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        chars = list(s)

        for char in t:
            if char in chars:
                chars.remove(char)
            else:
                return char






# Optimal:
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        count = [0] * 26

        for char in s:
            count[ord(char) - ord('a')] += 1

        for char in t:
            index = ord(char) - ord('a')
            count[index] -= 1

            if count[index] < 0:
                return char

        return ""